// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/harivanga-redesign/CleanMinimal.tsx": () => import("../components/mockups/harivanga-redesign/CleanMinimal.tsx"),
  "./components/mockups/harivanga-redesign/PremiumDark.tsx": () => import("../components/mockups/harivanga-redesign/PremiumDark.tsx"),
  "./components/mockups/harivanga-redesign/TropicalFresh.tsx": () => import("../components/mockups/harivanga-redesign/TropicalFresh.tsx")
};
